// Generated by Skyramp v1.3.29 on 2026-06-25 21:06:47.041165408 +0000 UTC m=+582.870855515
// Command: skyramp generate contract rest http://localhost:2285/api/server/version \
// 		--api-schema /home/runner/work/immich/immich/open-api/immich-openapi-specs.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_server_version.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/e2e/src/specs/server \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

// contract test for /api/server/version GET
test('testVersionGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedVersionGetResponseBody: string = `{
        "major": 3,
        "minor": 0,
        "patch": 0
    }`;

    // Execute Request
    const versionGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/server/version",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(versionGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(versionGetResponse, expectedVersionGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(versionGetResponse, "major"), 'value').not.toBeNull();
    expect(getResponseValue(versionGetResponse, "minor"), 'value').not.toBeNull();
    expect(getResponseValue(versionGetResponse, "patch"), 'value').not.toBeNull();
    expect(getResponseValue(versionGetResponse, "major"), 'major >= 0').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(versionGetResponse, "minor"), 'minor >= 0').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(versionGetResponse, "patch"), 'patch >= 0').toBeGreaterThanOrEqual(0);
});
