// Generated by Skyramp v1.3.29 on 2026-06-25 21:06:43.930425268 +0000 UTC m=+579.760115375
// Command: skyramp generate contract rest http://localhost:2285/api/server/about \
// 		--api-schema /home/runner/work/immich/immich/open-api/immich-openapi-specs.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_server_about.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/e2e/src/specs/server \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

// contract test for /api/server/about GET
test('testAboutGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedAboutGetResponseBody: string = `{
        "licensed": false,
        "version": "1.120.0",
        "versionUrl": "https://github.com/immich-app/immich/releases/tag/v1.120.0"
    }`;

    // Execute Request
    const aboutGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/server/about",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(aboutGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(aboutGetResponse, expectedAboutGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(aboutGetResponse, "licensed"), 'value').not.toBeNull();
    expect(getResponseValue(aboutGetResponse, "version"), 'value').not.toBeNull();
    expect(getResponseValue(aboutGetResponse, "versionUrl"), 'value').not.toBeNull();
    expect(getResponseValue(aboutGetResponse, "licensed"), 'licensed').toBe(false);
    expect(getResponseValue(aboutGetResponse, "version"), 'version matches semver').toMatch(/^v?\d+\.\d+\.\d+/);
    expect(getResponseValue(aboutGetResponse, "versionUrl"), 'versionUrl format').toMatch(/^https:\/\//);
});
