// Generated by Skyramp v1.3.29 on 2026-06-25 21:06:40.806009518 +0000 UTC m=+576.635699614
// Command: skyramp generate contract rest http://localhost:2285/api/server/media-types \
// 		--api-schema /home/runner/work/immich/immich/open-api/immich-openapi-specs.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_server_media_types.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/e2e/src/specs/server \
// 		--overwrite \
// 		--provider \
// 		--response-data {"sidecar":[".xmp"],"image":[".jpg",".png",".gif"],"video":[".mp4",".mov"],"count":6} \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2285");

// contract test for /api/server/media-types GET
test('testMediaTypesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedMediaTypesGetResponseBody: string = `{
        "count": 6,
        "image": [
            ".jpg",
            ".png",
            ".gif"
        ],
        "sidecar": [
            ".xmp"
        ],
        "video": [
            ".mp4",
            ".mov"
        ]
    }`;

    // Execute Request
    const mediaTypesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/server/media-types",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(mediaTypesGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(mediaTypesGetResponse, expectedMediaTypesGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(mediaTypesGetResponse, "count"), 'value').not.toBeNull();
    expect(getResponseValue(mediaTypesGetResponse, "image.0"), 'value').not.toBeNull();
    expect(getResponseValue(mediaTypesGetResponse, "image.1"), 'value').not.toBeNull();
    expect(getResponseValue(mediaTypesGetResponse, "count"), 'count >= 0').toBeGreaterThanOrEqual(0);
    expect(getResponseValue(mediaTypesGetResponse, "sidecar.0"), 'sidecar.0').toBe('.xmp');
    expect(getResponseValue(mediaTypesGetResponse, "sidecar.1"), 'sidecar.1 absent').toBeUndefined();
});
