// Generated by Skyramp v1.3.30 on 2026-06-29 19:37:44.162250913 +0000 UTC m=+605.989575494
// Command: skyramp generate contract rest http://localhost:2283/api/server/features \
// 		--api-schema open-api/immich-openapi-specs.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output server_features_contract_test.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/e2e/src/specs/server \
// 		--overwrite \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2283");

// contract test for /api/server/features GET
test('testFeaturesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedFeaturesGetResponseBody: string = `{
        "configFile": false,
        "duplicateDetection": false,
        "email": false,
        "facialRecognition": false,
        "importFaces": false,
        "map": false,
        "oauth": false,
        "oauthAutoLaunch": false,
        "ocr": false,
        "passwordLogin": false,
        "realtimeTranscoding": false,
        "reverseGeocoding": false,
        "search": false,
        "sidecar": false,
        "smartSearch": false,
        "trash": false
    }`;

    // Execute Request
    const featuresGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/server/features",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(featuresGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(featuresGetResponse, expectedFeaturesGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(featuresGetResponse, "configFile"), 'value').not.toBeNull();
    expect(getResponseValue(featuresGetResponse, "duplicateDetection"), 'value').not.toBeNull();
    expect(getResponseValue(featuresGetResponse, "email"), 'value').not.toBeNull();
    // Specific known values for server feature flags
    expect(getResponseValue(featuresGetResponse, "configFile")).toBe(false);
    expect(getResponseValue(featuresGetResponse, "passwordLogin")).toBe(true);
    expect(getResponseValue(featuresGetResponse, "trash")).toBe(true);
    expect(getResponseValue(featuresGetResponse, "sidecar")).toBe(true);
});
