// Generated by Skyramp v1.3.30 on 2026-06-29 19:37:41.562324513 +0000 UTC m=+603.389649094
// Command: skyramp generate contract rest http://localhost:2283/api/server/media-types \
// 		--api-schema open-api/immich-openapi-specs.json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output server_media_types_contract_test.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/e2e/src/specs/server \
// 		--overwrite \
// 		--provider \
// 		--response-data {"video":["video/mp4","video/mov","video/avi"],"image":["image/jpeg","image/png","image/webp"],"sidecar":[".xmp"],"count":7} \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2283");

// contract test for /api/server/media-types GET
test('testMediaTypesGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedMediaTypesGetResponseBody: string = `{
        "count": 7,
        "image": [
            "image/jpeg",
            "image/png",
            "image/webp"
        ],
        "sidecar": [
            ".xmp"
        ],
        "video": [
            "video/mp4",
            "video/mov",
            "video/avi"
        ]
    }`;

    // Execute Request
    const mediaTypesGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/server/media-types",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(mediaTypesGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(mediaTypesGetResponse, expectedMediaTypesGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(mediaTypesGetResponse, "count"), 'value').not.toBeNull();
    expect(getResponseValue(mediaTypesGetResponse, "image.0"), 'value').not.toBeNull();
    expect(getResponseValue(mediaTypesGetResponse, "image.1"), 'value').not.toBeNull();
    // Value ranges
    expect(getResponseValue(mediaTypesGetResponse, "count")).toBeGreaterThan(0);
    // Specific known values
    expect(getResponseValue(mediaTypesGetResponse, "sidecar.0")).toBe(".xmp");
});
