// Generated by Skyramp v1.3.30 on 2026-06-29 19:38:00.966273224 +0000 UTC m=+622.793597805
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_media_types_count_validation_integration_test.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/e2e/src/specs/server \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/immich/immich/e2e/src/specs/server/scenario_server_media_types_count_validation.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:2283");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const pingGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/server/ping",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(pingGetResponse.statusCode, 'status code').toBe(200);
    // Specific known values
    expect(getValue(pingGetResponse, "res")).toBe("pong");

    // Execute Request
    const mediaTypesGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/server/media-types",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(mediaTypesGetResponse.statusCode, 'status code').toBe(200);
    // Value ranges
    expect(getValue(mediaTypesGetResponse, "count")).toBeGreaterThan(0);
    // Specific known values
    expect(getValue(mediaTypesGetResponse, "sidecar.0")).toBe(".xmp");
});
