// Generated by Skyramp v1.3.29 on 2026-06-25 19:04:29.020115978 +0000 UTC m=+716.907034853
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output demo_note_visibility.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/tests/skyramp/web \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich/immich/.skyramp/demo_note_visibility_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:2285/auth/login");
    await expect(page).toHaveURL(/\/auth\/login/);
    await expect(page.getByRole('heading', { name: 'Login' })).toBeVisible();
    await expect(page.getByTestId("demo-instance-note")).toHaveText("Skyramp Testbot demo instance");
    expect(errors).toHaveLength(0);
});
