// Generated by Skyramp v1.3.29 on 2026-06-25 19:04:31.907494209 +0000 UTC m=+719.794413074
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_error.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/tests/skyramp/web \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich/immich/.skyramp/login_error_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(104000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:2285/auth/login");
    await page.locator("#email").fill("admin@immich.test");
    await page.locator("#password").fill("wrongpassword");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/auth\/login/);
    await expect(page.getByText("Incorrect email or password")).toBeVisible();
    await expect(page.getByTestId("demo-instance-note")).toHaveText("Skyramp Testbot demo instance");
    expect(errors).toHaveLength(0);
});
