// Generated by Skyramp v1.3.29 on 2026-06-25 19:04:30.963838624 +0000 UTC m=+718.850757489
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output login_success.spec.ts \
// 		--output-dir /home/runner/work/immich/immich/tests/skyramp/web \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/immich/immich/.skyramp/login_success_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);
    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:2285/auth/login");
    await page.locator("#email").fill("admin@immich.test");
    await page.locator("#password").fill("password");
    await page.getByRole("button", { name: "Login" }).click();
    await expect(page).toHaveURL(/\/auth\/onboarding/);
    await expect(page.getByRole('button', { name: 'Theme' })).toBeVisible();
    expect(errors).toHaveLength(0);
});
